services:
    db:
        image: mysql:8.4.0
        container_name: map_market_db
        command: mysqld --mysql_native_password=ON
        restart: always
        environment:
            TZ: America/Sao_Paulo
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_HOST: '%'
            MYSQL_TCP_PORT: ${MYSQL_TCP_PORT}
        ports:
            - "${MYSQL_TCP_PORT}:${MYSQL_TCP_PORT}"
        networks:
            - map-market-network
            
    map-market_frontend:
        build:
          context: ./frontend
          args:
            - API_URL=${API_URL}
        image: vaiento/map-market-frontend
        container_name: map_market_frontend
        restart: always
        ports:
            - "4200:4200"
        environment:
            TZ: America/Sao_Paulo
        networks:
            - map-market-network
        depends_on:
            - map-market_backend

    map-market_backend:
        build: ./backend
        image: vaiento/map-market-backend
        container_name: map_market_backend
        restart: always
        working_dir: /backend
        environment:
            TZ: America/Sao_Paulo
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
            SECRET_KEY: ${SECRET_KEY}
            CLIENT_ORIGIN: ${CLIENT_ORIGIN}
            EXPIRE_TIME: ${EXPIRE_TIME}
        ports:
            - "8080:8080"
        depends_on:
            - db
        networks:
            - map-market-network

networks:
    map-market-network:
        name: map-market-network
        driver: bridge
