cors:
    allowed-origins: http://localhost:4200
security:
    jwt:
        token:
            secret-key: 147258
            expire-length: 3600000
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: endereco_do_db
        username: seu_usuario
        password: seu_password
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
logging:
    level:
        org.hibernate.orm.connections.pooling: WARN
flyway:
    enabled: true
    locations: classpath:db.migration